### ISSUE TITLE
qrycmd.go:704 Incorrect number of bytes read from connection

### ISSUE THREAD

**Issue by larryaasen** [istreamdata/orientgo#23] opened 2015-08-30 03:32 UTC
Hi Michael,

I have been using ogonori successfully now for a few months on a RESTful server about to be released. Have not had any issues in a while. Just yesterday I started having an issue with incorrect number of bytes read using obinary.SQLQuery with the latest code from master. This error does not happen all the time and I cannot seem to duplicate the error on my test server.

Here is my log:
github.com/quux00/ogonori/obinary/qrycmd.go:125; cause: github.com/quux00/ogonori/obinary/qrycmd.go:704; cause: Incorrect number of bytes read from connection. Expected: 2; Actual: 1

Here was my SQL:
SELECT FROM Post WHERE @RID IN [#15:772, #15:770, #15:769, #15:683, #15:682, #15:681, #15:680, #15:678, #15:615, #15:614, #15:580, #15:579, #15:577, #15:499, #15:260, #15:234, #15:185, #15:164, #15:157, #15:155, #15:154, #15:153, #15:149, #15:138, #15:135, #15:128, #15:122, #15:116, #15:115, #15:109, #15:108, #15:107, #15:106, #15:105, #15:104, #15:103, #15:102, #15:101, #15:100, #15:98, #15:85, #15:78, #15:72, #15:60, #15:58, #15:29, #15:28, #15:22, #15:8]

If you have any idea why this might be failing or how I could prevent this error, please let me know.

Thanks again for creating this package for us.

Larry

**Comment by quux00** [comment] 2015-08-31 01:19
Hi Larry,

I'm pretty this is the same problem as that of Issue #7 (and Issue #18, which was merged into 7).  I have not researched why this happens.  In my experience and that of @ernestas-poskus (who reported #18), it is when a "large" dataset is returned.  The value of large seems to vary.  At first I only saw it for >64KiB, but on Windows it was seen for something like a ~4KiB return value. 

So two possible reasons as to why you are seeing it now are:

1. Did you change versions of OrientDB?  ogonori does not work with the 2.1 series yet for reasons not yet researched.

2. The size of the record(s) returned from the query you are doing has increased - either because your are querying more records or the size of one of the fields of a record has increased to a size that uncovers the flaw.

I will move this issue up the priority stack.  It should be reproducible by simply making the size of a field to be "large" (for some value of large).  Then I can compare what the db is returning in the ogonori version vs. the Java client.

@ernestas-poskus - in Issue #18 you said you might work on figuring this out.  Have you had a chance to do that?

**Comment by larryaasen** [comment] 2015-09-02 01:31
I appreciate you looking into this issue. It seem intermittent and I don't think it has to do with the size of the response. Sometimes it happens when I query for 49 records at a time, and sometimes when I query 100 records, where each record is about the same size. I will continue to find a repo case that I can send you. In the meantime, I don't have many details to offer you.

**Comment by ernestas-poskus** [comment] 2015-09-03 20:09
I didn't had a change to dig at this yet. IMO the issue is with single connection and concurrent usage.

**Comment by quux00** [comment] 2015-09-04 00:50
Larry,

Are you running multiple goroutines in the code that hits the error?  If so, are they sharing a DBClient object?

**Comment by larryaasen** [comment] 2015-09-04 02:30
I do run multiple goroutines using Gin but I create a new connection for each one using obinary.NewDBClient().

**Comment by ernestas-poskus** [comment] 2015-09-04 15:40
There might be more problems like leaking TCP connection or latency if app and server on different servers

**Comment by dennwc** [comment] 2015-09-06 15:58
@larryaasen Can you please try to reproduce issue in this [fork](https://github.com/istreamdata/orientgo)? I think that it should not be affected by the issue.

@quux00 @ernestas-poskus Seems that this code part causes the error:
```Go
 // obinary/rw/reader.go:62
func ReadBytes(rdr io.Reader) ([]byte, error) {
	// ...
	readbuf := make([]byte, sz)
	n, err := rdr.Read(readbuf)
	if err != nil {
		return nil, oerror.NewTrace(err)
	}
	// ...
```
As [doc says](http://golang.org/pkg/io/#Reader), `Read` is not guarantied to read exactly `len(p)` bytes, but `0 <= n <= len(p)`. Issue #7 clearly shown this, because actual read size was at most 32Kb long, which should be internal buffer size of network connection, or something similar. You could use [io.ReadFull](http://golang.org/pkg/io/#ReadFull) instead - it tries to read whole buffer and returns error if it can't.

**Comment by quux00** [comment] 2015-09-09 00:28
@dennwc Thanks very much for the suggestion.  I haven't had a chance to try the fix yet.  I like what you guys are doing on orientgo.  Are you part of that project?

**Comment by larryaasen** [comment] 2015-09-12 20:50
@dennwc Sorry, but I am not seeing this issue anymore using the main branch. I will keep looking for a repo case and will let you know if I find one.

**Comment by ernestas-poskus** [comment] 2015-09-13 11:50
> Ownership of the ogonori library is being transferred to the istreamdata team

good news :+1:

**Comment by dennwc** [comment] 2015-09-16 18:13
I assume, that this issue is resolved, as our code has been merged and we have not seen this behavior.

**Closed by dennwc** 2015-09-16 18:13 UTC
Labels: bug

**Comment by larryaasen** [comment] 2015-09-22 02:08
I just noticed this issue again but I am using code from Aug. 29th. I am not sure if I should upgrade my package because I am using 'quux00/ogonori/' and now it is named 'istreamdata/orientgo'.

Are there any upgrading issues that I should be aware of?

**Comment by dennwc** [comment] 2015-09-22 07:20
If you don't need additional functionality you can safely change import paths to new repo, as `v1` branch still points to ogonori code. Also, a made a fix for this issue for `v1`, so there is a reason for upgrading you code. Please download new package using `go get -u gopkg.in/istreamdata/ogonori.v1` and change imports to `gopkg.in/istreamdata/ogonori.v1/obinary` - this should fix an issue.

**Comment by larryaasen** [comment] 2015-09-22 11:16
Hi Denys,

Thanks for the details. I will try the upgrade and see if it solve this issue and let you know.

Larry
